// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCigapMtSnhuWSeczVu34Ryj2I2Y-kufxo',
    appId: '1:818067624520:web:563f7e9e3e94af88b3fe7d',
    messagingSenderId: '818067624520',
    projectId: 'booknest-60670',
    authDomain: 'booknest-60670.firebaseapp.com',
    storageBucket: 'booknest-60670.firebasestorage.app',
    measurementId: 'G-SL4686S71C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzzsTYK9twtcP2KPO6mjPWOIUO5GI7iKI',
    appId: '1:818067624520:android:e4fa15eeae9aaaeab3fe7d',
    messagingSenderId: '818067624520',
    projectId: 'booknest-60670',
    storageBucket: 'booknest-60670.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjaGK_0zb_88YGH6U-DBS-mmFqtkXpjNg',
    appId: '1:818067624520:ios:d88e4f00c53c5d24b3fe7d',
    messagingSenderId: '818067624520',
    projectId: 'booknest-60670',
    storageBucket: 'booknest-60670.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjaGK_0zb_88YGH6U-DBS-mmFqtkXpjNg',
    appId: '1:818067624520:ios:d88e4f00c53c5d24b3fe7d',
    messagingSenderId: '818067624520',
    projectId: 'booknest-60670',
    storageBucket: 'booknest-60670.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCigapMtSnhuWSeczVu34Ryj2I2Y-kufxo',
    appId: '1:818067624520:web:a9f00d45ad069178b3fe7d',
    messagingSenderId: '818067624520',
    projectId: 'booknest-60670',
    authDomain: 'booknest-60670.firebaseapp.com',
    storageBucket: 'booknest-60670.firebasestorage.app',
    measurementId: 'G-GF2N8J7Y1J',
  );
}
